Improve unit testing
Hello,

I would like to contribute to Qkan but not having unit testing support makes it hard as I don't want to break stuff :sos: . My idea was to use mocking for separate GUI components from business logic. The main idea is shown within the `TestM145Porter` class using the `mock_imports` function. Apparently, the project is using initialization with `__init__.py` files heavily which make mocking harder e.g. currently I'm 'stuck with:
```  File "C:\Users\Moddus\PycharmProjects\QKan\qkan\tools\dialogs\dbAdapt.py", line 23, in <module>
    class DbAdaptDialog(QKanDBDialog, QKanProjectDialog, FORM_CLASS_dbAdapt):  # type: ignore
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases```
where multi class inheritance is use by statically creating `FORM_CLASS_dbAdapt`.

As I'm not an expert, yet :smile: . Could you explain the need to importing using `__init__.py` files or would it be possible to use some additional layer to abstract? I'm not sure if the current structure is given by the QGIS plugin API. I inspect a few popular plugins but I couldn't find the same pattern as in Qkan.

Thanks for working on Qkan! Thanks for taking the time to read this :)

Happy to get suggestions/comments.